import data from '../data/cities.json'

// Generated by scripts/build-cities.mjs (GeoNames, CC BY 4.0). Rows are compact
// arrays: [name, nameRu, countryCode, admin1, lat, lng, timezone, population].
// They arrive in chunks because Hermes caps array literals at 65535 elements.
const ROWS = (data.chunks || []).flat()
const COUNTRIES = data.countries || {}
const REGIONS = data.regions || {}

const stripDiacritics = (value) => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '')
const normalize = (value) => stripDiacritics(value).toLowerCase().replace(/ё/g, 'е')

function regionNames(cc, admin1) {
  return REGIONS[`${cc}.${admin1}`] || null
}

function countryNames(cc) {
  return COUNTRIES[cc] || null
}

const regionNormCache = new Map()
function normalizedRegion(cc, admin1) {
  const key = `${cc}.${admin1}`
  const cached = regionNormCache.get(key)
  if (cached) return cached
  const region = regionNames(cc, admin1)
  const value = region ? [normalize(region[0]), normalize(region[1] || region[0])] : ['', '']
  regionNormCache.set(key, value)
  return value
}

// Lowercased search indexes built once at startup.
const NAME = new Array(ROWS.length)
const RU = new Array(ROWS.length)
const REGION_EN = new Array(ROWS.length)
const REGION_RU = new Array(ROWS.length)

for (let i = 0; i < ROWS.length; i++) {
  const row = ROWS[i]
  if (!row) continue
  const [name, ru, cc, admin1] = row
  const region = normalizedRegion(cc, admin1)
  NAME[i] = normalize(name)
  // Empty when there is no real Russian name so it cannot outrank a proper match.
  RU[i] = ru ? normalize(ru) : ''
  REGION_EN[i] = region[0]
  REGION_RU[i] = region[1]
}

function toCity(row) {
  const [name, ru, cc, admin1, latitude, longitude, timezone, population] = row
  const region = regionNames(cc, admin1)
  const country = countryNames(cc)
  return {
    name,
    nameRu: ru || name,
    country: country ? country[0] : cc,
    countryRu: country ? country[1] || country[0] : cc,
    region: region ? region[0] : '',
    regionRu: region ? region[1] || region[0] : '',
    latitude,
    longitude,
    timezone,
    population,
  }
}

// Mirrors the app locale ('ru' | 'en') so results are ranked by the name the
// user actually sees, while still matching both languages and the region.
export function searchCities(query, lang = 'ru') {
  const q = normalize(query).trim()
  if (q.length === 0) return []

  const preferRu = lang === 'ru'
  const matches = []
  for (let i = 0; i < ROWS.length; i++) {
    const nameHit = NAME[i].includes(q)
    const ruHit = RU[i] !== '' && RU[i].includes(q)
    if (!nameHit && !ruHit) {
      if (!REGION_EN[i].includes(q) && !REGION_RU[i].includes(q)) continue
      matches.push([4, ROWS[i][7], i])
      continue
    }

    const prefName = preferRu ? RU[i] : NAME[i]
    const prefHit = preferRu ? ruHit : nameHit
    const altName = preferRu ? NAME[i] : RU[i]
    const altHit = preferRu ? nameHit : ruHit
    const rank = prefHit ? (prefName.startsWith(q) ? 0 : 1) : altHit ? (altName.startsWith(q) ? 2 : 3) : 4
    matches.push([rank, ROWS[i][7], i])
  }

  matches.sort((a, b) => a[0] - b[0] || b[1] - a[1])
  return matches.slice(0, 10).map(([, , index]) => toCity(ROWS[index]))
}

export function cityPrimary(city, lang = 'ru') {
  if (!city) return ''
  return (lang === 'ru' ? city.nameRu || city.name : city.name) || ''
}

export function citySecondary(city, lang = 'ru') {
  if (!city) return ''
  const region = lang === 'ru' ? city.regionRu || city.region : city.region
  const country = lang === 'ru' ? city.countryRu || city.country : city.country
  return [region, country].filter(Boolean).join(', ')
}
